# Generated by Django 5.1.1 on 2024-11-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('CodigoU', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('ArchivoU', models.ImageField(blank=True, null=True, upload_to='Aplicaciones/Universidad/static/imagenes/')),
                ('FotoU', models.CharField(max_length=150)),
                ('Perfil', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('CodigoB', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Subtitulo', models.CharField(max_length=100)),
                ('Cuerpo', models.CharField(max_length=250)),
                ('Fecha', models.DateField()),
                ('ArchivoB', models.ImageField(blank=True, null=True, upload_to='Aplicaciones/Universidad/static/imagenes/')),
                ('FotoB', models.CharField(max_length=150)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universidad.usuarios')),
            ],
        ),
    ]
