# Generated by Django 5.1.1 on 2024-10-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('CodigoC', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Camada', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregables',
            fields=[
                ('CodigoEn', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('FechaDeEntrega', models.DateField()),
                ('Entregado', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('CodigoE', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('CodigoP', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
